apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLDatabase
metadata:
  name: {{ .Values.dbName }}
  labels: 
  {{- include "labels" . | indent 4 }}
spec:
  charset: utf8mb4
  collation: utf8mb4_bin
  instanceRef:
    name: {{ .Values.dbName }}-instance