apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLDatabase
metadata:
  name: {{ .Values.dbName }}
  labels: 
  {{- include "labels" . | indent 4 }}
spec:
  charset: UTF8
  collation: en_US.UTF8
  instanceRef:
    name: {{ .Values.dbName }}-instance