apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeAddress
metadata:
  name: {{ .Values.dbName }}-private-network
  labels: 
  {{- include "labels" . | indent 4 }}
spec:
  addressType: INTERNAL
  location: global
  purpose: VPC_PEERING
  prefixLength: 16
  networkRef:
    name: {{ .Values.dbName }}-private-network
