apiVersion: servicenetworking.cnrm.cloud.google.com/v1beta1
kind: ServiceNetworkingConnection
metadata:
  name: {{ .Values.dbName }}-private-network
  labels: 
  {{- include "labels" . | indent 4 }}
spec:
  networkRef:
    name: {{ .Values.dbName }}-private-network
  reservedPeeringRanges:
    - name: {{ .Values.dbName }}-private-network
  service: servicenetworking.googleapis.com